ghcnd_stations:  https://www.ncei.noaa.gov/pub/data/ghcn/daily/ghcnd-stations.txt
ghcnd_readme:    https://www1.ncdc.noaa.gov/pub/data/ghcn/daily/by_station/readme-by_station.txt
ghcnd_inventory: https://www.ncei.noaa.gov/pub/data/ghcn/daily/ghcnd-inventory.txt
ghcnd_path:      https://www1.ncdc.noaa.gov/pub/data/ghcn/daily/by_station/
station:         NZM00093110
name:            Auckland Aero
